// <auto-generated />
namespace LocalSpirits.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _4force : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4force));
        
        string IMigrationMetadata.Id
        {
            get { return "202011281758368_4-force"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
