// <auto-generated />
namespace LocalSpirits.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_13));
        
        string IMigrationMetadata.Id
        {
            get { return "202011300234423_13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
